name       : squashfuse
version    : 0.1.104
release    : 3
source     :
    - https://github.com/vasi/squashfuse/releases/download/0.1.104/squashfuse-0.1.104.tar.gz : aa52460559e0d0b1753f6b1af5c68cfb777ca5a13913285e93f4f9b7aa894b3a
license    : BSD-2-Clause
component  : system.utils
summary    : FUSE filesystem to mount squashfs archives
description: |
    FUSE filesystem to mount squashfs archives
builddeps  :
    - pkgconfig(fuse3)
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
