name       : squashfuse
version    : 0.1.103
release    : 2
source     :
    - https://github.com/vasi/squashfuse/releases/download/0.1.103/squashfuse-0.1.103.tar.gz : 42d4dfd17ed186745117cfd427023eb81effff3832bab09067823492b6b982e7
license    : BSD-2-Clause
component  : system.utils
summary    : FUSE filesystem to mount squashfs archives
description: |
    FUSE filesystem to mount squashfs archives
builddeps  :
    - pkgconfig(fuse)
rundeps    :
    - fuse2
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 *.h -t $installdir/usr/include/squashfuse
    sed -e 's|\#include \"|\#include \"squashfuse\/|g' -i $installdir/usr/include/squashfuse.h
